# Generated by Django 3.2.6 on 2021-08-29 20:56

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración de un Sprint'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado_de_proyecto',
            field=models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 20, 56, 25, 226992, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 29, 20, 56, 25, 226917, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del rol')),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
            ],
            options={
                'permissions': (('p_administrar_sprints', 'Permite que el usuario pueda crear, configurar y borrar los sprints del proyecto. Además tendrá la capacidad de alargar y de terminar el sprint en cualquier momento. Podrá también planificar un nuevo sprint.'), ('p_administrar_user_stories', 'Con este permiso el usuario podrá crear nuevos user stories y podrá modificar los user stories.'), ('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_usuarios', 'Puede asignar nuevos usuarios al proyecto o darles de baja.'), ('stakeholder', 'El usuario podrá ver los sprints, el Kanban y los user storys pero no podrá cambiar algo.')),
            },
        ),
    ]
