# Generated by Django 3.2.6 on 2021-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre del rol')),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
            ],
            options={
                'permissions': (('p_administrar_sprints', 'Permite que el usuario pueda crear, configurar y borrar los sprints del proyecto. Además tendrá la capacidad de alargar y de terminar el sprint en cualquier momento. Podrá también planificar un nuevo sprint.'), ('p_administrar_user_stories', 'Con este permiso el usuario podrá crear nuevos user stories y podrá modificar los user stories.'), ('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_usuarios', 'Puede asignar nuevos usuarios al proyecto o darles de baja.'), ('p_stakeholder', 'El usuario podrá ver los sprints, el Kanban y los user storys pero no podrá cambiar algo.')),
            },
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
