# Generated by Django 3.2.6 on 2021-10-04 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_acceder_proyectos', 'Permiso de acceder proyecto.'), ('p_cancelar_proyectos', 'Permiso de cancelar proyecto.'), ('p_editar_proyectos', 'Permiso de editar proyecto.'), ('p_finalizar_proyectos', 'Permiso de finalizar proyecto.'), ('p_administrar_participantes', 'Permiso para agregar y eliminar participantes del proyecto.'), ('p_administrar_roles', 'Permite que el usuario pueda agregar, editar, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_sprint', 'Permite que el usuario pueda gestionar los parámetros de los sprints, así como planificarlos, iniciarlos y finalizarlos.'), ('p_administrar_us', 'Permite que el usuario pueda agregar, editar y eliminar los user stories del proyecto.'))},
        ),
        migrations.AddField(
            model_name='sprint',
            name='carga_horaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de horas de todos los user storys asignados', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectuser'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tiempo_promedio_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de duración promedio entre los dos tiempos estimados.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_estimado_dev',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo de duración estimado por el desarrollador asignado.', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_estimado_scrum_master',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo de duración estimado por el scrum master.', null=True),
        ),
    ]
