# Generated by Django 3.2.6 on 2021-10-11 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userstory',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyectuser'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='product_backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.productbacklog'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='rolproyecto',
            name='participantes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolproyecto',
            name='permisos',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='rolproyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='proyectuser',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_team', to='proyecto.sprint'),
        ),
        migrations.AddField(
            model_name='proyectuser',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo_desarrollador',
            field=models.ManyToManyField(blank=True, to='proyecto.ProyectUser'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.AddField(
            model_name='historialus',
            name='us_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.userstory'),
        ),
        migrations.AddField(
            model_name='daily',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sprint'),
        ),
        migrations.AddField(
            model_name='daily',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.userstory'),
        ),
    ]
