# Generated by Django 3.2.6 on 2021-09-03 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_acceder_proyectos', 'Permiso de acceder proyecto.'), ('p_cancelar_proyectos', 'Permiso de cancelar proyecto.'), ('p_editar_proyectos', 'Permiso de editar proyecto.'), ('p_finalizar_proyectos', 'Permiso de finalizar proyecto.'))},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración de un Sprint'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='estado_de_proyecto',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inicializado'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 17, 20, 3, 577081, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 17, 20, 3, 577030, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
        migrations.CreateModel(
            name='RolProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre del rol')),
                ('participantes', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('permisos', models.ManyToManyField(to='auth.Permission')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto')),
            ],
            options={
                'permissions': (('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'),),
            },
        ),
    ]
