# Generated by Django 3.2.6 on 2021-08-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración de un Sprint'),
        ),
    ]
