# Generated by Django 3.2.6 on 2021-08-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolsistema',
            name='permisos',
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolSistema',
        ),
    ]
