# Generated by Django 3.2.6 on 2021-08-30 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210829_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_crear_proyecto', 'Permiso de crear nuevos proyectos.'), ('p_acceder_proyectos', 'Permiso de acceder proyectos.'))},
        ),
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'permissions': (('p_administrar_sprints', 'Permite que el usuario pueda crear, configurar y borrar los sprints del proyecto. Además tendrá la capacidad de alargar y de terminar el sprint en cualquier momento. Podrá también planificar un nuevo sprint.'), ('p_administrar_user_stories', 'Con este permiso el usuario podrá crear nuevos user stories y podrá modificar los user stories.'), ('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_usuarios', 'Puede asignar nuevos usuarios al proyecto o darles de baja.'), ('p_stakeholder', 'El usuario podrá ver los sprints, el Kanban y los user storys pero no podrá cambiar algo.'))},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 21, 58, 38, 832553, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 21, 58, 38, 832523, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
