# Generated by Django 3.2.6 on 2021-09-13 23:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210903_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 23, 3, 43, 350630, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 13, 23, 3, 43, 350603, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
