# Generated by Django 3.2.6 on 2021-08-21 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210821_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'permissions': (('p_administrar_sprints', 'Permite que el usuario pueda crear, configurar y borrar los sprints del proyecto. Además tendrá la capacidad de alargar y de terminar el sprint en cualquier momento. Podrá también planificar un nuevo sprint.'), ('p_administrar_user_stories', 'Con este permiso el usuario podrá crear nuevos user stories y podrá modificar los user stories.'), ('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_usuarios', 'Puede asignar nuevos usuarios al proyecto o darles de baja.'), ('stakeholder', 'El usuario podrá ver los sprints, el Kanban y los user storys pero no podrá cambiar algo.'))},
        ),
    ]
