# Generated by Django 3.2.6 on 2021-08-23 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210823_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
