# Generated by Django 3.2.6 on 2021-08-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_proyecto_duracionsprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado_de_proyecto',
            field=models.CharField(choices=[('A', 'Activo'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='A', max_length=1),
        ),
    ]
