# Generated by Django 3.2.6 on 2021-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_userstory_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='tiempo_promedio_calculado',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de duración promedio entre los dos tiempos estimados.', null=True),
        ),
    ]
