# Generated by Django 3.2.6 on 2021-10-05 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20211004_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={},
        ),
    ]
