# Generated by Django 3.2.6 on 2021-10-29 03:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_historialus_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_acceder_proyecto', 'Permiso de acceder al proyecto.'), ('p_cancelar_proyectos', 'Permiso de cancelar proyecto.'), ('p_editar_proyectos', 'Permiso de editar proyecto.'), ('p_finalizar_proyectos', 'Permiso de finalizar proyecto.'), ('p_administrar_participantes', 'Permiso para agregar y eliminar participantes del proyecto.'), ('p_administrar_roles', 'Permite que el usuario pueda agregar, editar, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'), ('p_administrar_sprint', 'Permite que el usuario pueda gestionar los parámetros de los sprints, así como planificarlos, iniciarlos y finalizarlos.'), ('p_administrar_us', 'Permite que el usuario pueda editar los user stories del proyecto (cambiar estado, nombre, descripción y horas).'), ('p_eliminar_us', 'Permite que el usuario pueda eliminar user stories del proyecto (cambiar estado, nombre, descripción y horas).'), ('p_administrar_us_qa', 'Con este permiso el usuario puede cambiar el estado de un user story a QA. Inicialmente es un permiso reservado al scrum master.'), ('p_aprobar_us', 'Con este permiso el usuario puede agregar un user story en estado no aprobado, así como también modificarlo y aprobarlo para que pase al product backlog.'), ('p_eliminar_daily', 'Permite que el usuario pueda eliminar el daily asociado a un user story.'), ('p_administrar_devs', 'Con este permiso el usuario puede gestionar los desarrolladores en un sprint.'))},
        ),
        migrations.AddField(
            model_name='historialus',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historialus',
            name='log',
            field=models.TextField(blank=True, verbose_name='Log en donde se almacenan los cambios de estado en el ciclo de vida del User Story'),
        ),
        migrations.AddField(
            model_name='historialus',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sprint'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='fechaFinalizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración estimada en días hábiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
