# Generated by Django 3.2.6 on 2021-08-30 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20210829_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_crear_proyecto', 'Permiso de crear nuevos proyectos.'), ('p_acceder_proyectos', 'Permiso de acceder proyectos.'))},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 21, 44, 15, 812439, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 21, 44, 15, 812406, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
