# Generated by Django 3.2.6 on 2021-10-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_rolproyecto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateField(help_text='Fecha estimada de finalización del Sprint. Dependiendo de esta fecha se mostrarán alertas.', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del user story'),
        ),
    ]
