# Generated by Django 3.2.6 on 2021-09-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_userstory_tiempo_promedio_calculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_estimado_dev',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo de duración estimado por el desarrollador asignado.', null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_estimado_scrum_master',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo de duración estimado por el scrum master.', null=True),
        ),
    ]
