# Generated by Django 3.2.6 on 2021-08-30 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20210830_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 23, 5, 25, 265874, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 23, 5, 25, 265828, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
