# Generated by Django 3.2.6 on 2021-09-09 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0004_auto_20210908_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_diarias', models.DecimalField(decimal_places=2, help_text='La cantidad de horas que trabaja el desarrollador por día.', max_digits=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo_desarrollador',
            field=models.ManyToManyField(blank=True, to='proyecto.ProyectUser'),
        ),
    ]
