# Generated by Django 3.2.6 on 2021-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20211118_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_estimado_dev',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Tiempo de duración estimado por el desarrollador asignado.', null=True),
        ),
    ]
