# Generated by Django 3.2.6 on 2021-09-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20210919_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='tiempo_promedio_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tiempo de duración promedio entre los dos tiempos estimados.', max_digits=4, null=True),
        ),
    ]
