# Generated by Django 3.2.6 on 2021-08-30 23:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20210830_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 23, 23, 31, 29589, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 30, 23, 23, 31, 29557, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
        migrations.AlterField(
            model_name='rolproyecto',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
