# Generated by Django 3.2.6 on 2021-09-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20210903_2124'),
        ('proyecto', '0004_auto_20210908_0015'),
    ]

    operations = [
    ]
