# Generated by Django 3.2.6 on 2021-09-11 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_auto_20210909_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(default='Sprint', max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField(help_text='Fecha estimada de finalización del Sprint')),
                ('duracionSprint', models.IntegerField(default=14, help_text='Duración estimada del Sprint', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='duracionSprint',
        ),
    ]
