# Generated by Django 3.2.6 on 2021-08-31 19:24

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0005_auto_20210830_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolproyecto',
            name='participantes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 19, 24, 28, 340424, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 31, 19, 24, 28, 340363, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
