# Generated by Django 3.2.6 on 2021-09-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_alter_userstory_tiempo_promedio_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='carga_horaria',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de horas de todos los user storys asignados', max_digits=4, null=True),
        ),
    ]
