# Generated by Django 3.2.6 on 2021-09-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20210911_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='estado_de_sprint',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inicializado'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='I', max_length=1),
        ),
    ]
