# Generated by Django 3.2.6 on 2021-09-01 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_auto_20210831_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_acceder_proyectos', 'Permiso de acceder proyecto.'),)},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 22, 19, 893203, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 22, 19, 893170, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
