# Generated by Django 3.2.6 on 2021-09-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_sprint_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateField(help_text='Fecha estimada de finalización del Sprint. Dependiendo de esta fecha se mostrarán alertas.', null=True),
        ),
    ]
