# Generated by Django 3.2.6 on 2021-08-27 00:59

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyecto', '0006_auto_20210827_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 0, 59, 43, 439123, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 0, 59, 43, 439089, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
