# Generated by Django 3.2.6 on 2021-09-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_alter_sprint_fechafin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del user story'),
        ),
    ]
