# Generated by Django 3.2.6 on 2021-09-01 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20210901_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'permissions': (('p_acceder_proyectos', 'Permiso de acceder proyecto.'), ('p_cancelar_proyectos', 'Permiso de cancelar proyecto.'), ('p_editar_proyectos', 'Permiso de editar proyecto.'), ('p_finalizar_proyectos', 'Permiso de finalizar proyecto.'))},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 23, 44, 607684, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 23, 44, 607654, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
