# Generated by Django 3.2.6 on 2021-08-27 01:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20210827_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 1, 7, 12, 852467, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 27, 1, 7, 12, 852435, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
