# Generated by Django 3.2.6 on 2021-09-01 01:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_auto_20210901_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 28, 51, 631766, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 28, 51, 631735, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
