# Generated by Django 3.2.6 on 2021-09-11 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0008_sprint_equipo_desarrollador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración estimad en días', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaFin',
            field=models.DateField(help_text='Fecha estimada de finalización del Sprint. Dependiendo de esta fecha se mostrarán alertas.'),
        ),
    ]
