# Generated by Django 3.2.6 on 2021-08-28 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20210827_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 2, 31, 22, 887249, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 2, 31, 22, 887197, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
