# Generated by Django 3.2.6 on 2021-10-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20211005_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='last_estimated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
