# Generated by Django 3.2.6 on 2021-09-11 22:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20210911_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='duracionSprint',
            field=models.IntegerField(default=14, help_text='Duración estimada en días', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
