# Generated by Django 3.2.6 on 2021-09-01 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0009_auto_20210901_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolproyecto',
            options={'permissions': (('p_administrar_roles', 'Permite que el usuario pueda configurar, crear, importar y eliminar roles del proyecto. Solo los permisos del scrum master no se podrán modificar.'),)},
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 32, 14, 782871, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 1, 32, 14, 782837, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
