# Generated by Django 3.2.6 on 2021-09-11 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0010_alter_sprint_duracionsprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
            preserve_default=False,
        ),
    ]
