# Generated by Django 3.2.6 on 2021-09-13 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_sprint_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='equipo_desarrollador',
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
        migrations.CreateModel(
            name='SprintDevTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_team', to='proyecto.sprint')),
                ('team', models.ManyToManyField(blank=True, to='proyecto.ProyectUser')),
            ],
        ),
    ]
