# Generated by Django 3.2.6 on 2021-09-14 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_sprint_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='equipo_desarrollador',
        ),
        migrations.AddField(
            model_name='proyectuser',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_team', to='proyecto.sprint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprint',
            name='fechaInicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.proyecto'),
        ),
    ]
