# Generated by Django 3.2.6 on 2021-09-14 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20210913_2303'),
        ('proyecto', '0005_merge_0003_auto_20210903_2124_0004_auto_20210908_0015'),
        ('proyecto', '0012_auto_20210913_2340'),
    ]

    operations = [
    ]
