# Generated by Django 3.2.6 on 2021-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0012_auto_20210914_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del user story')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción del user story')),
                ('tiempoEstimado', models.PositiveIntegerField()),
                ('estado_user_story', models.CharField(choices=[('TD', 'To do'), ('DG', 'Doing'), ('DN', 'Done'), ('QA', 'Quality Assurance')], default='TD', max_length=2)),
            ],
        ),
    ]
