# Generated by Django 3.2.6 on 2021-09-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_userstory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='tiempoEstimado',
        ),
        migrations.AddField(
            model_name='userstory',
            name='estado_aprobacion',
            field=models.CharField(choices=[('T', 'Temporal'), ('A', 'Aprobado')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='prioridad_user_story',
            field=models.CharField(choices=[('B', 'Baja'), ('A', 'Alta'), ('M', 'Media'), ('E', 'Emergencia')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='userstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.sprint'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tiempo_estimado_dev',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de duración estimado por el desarrollador asignado.', null=True),
        ),
        migrations.AddField(
            model_name='userstory',
            name='tiempo_estimado_scrum_master',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo de duración estimado por el scrum master.', null=True),
        ),
    ]
