# Generated by Django 3.2.6 on 2021-09-03 03:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0013_auto_20210901_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 3, 46, 27, 970625, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 3, 46, 27, 970575, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
