# Generated by Django 3.2.6 on 2021-09-03 01:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20210902_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado_de_proyecto',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inicializado'), ('C', 'Cancelado'), ('F', 'Finalizado')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 1, 54, 48, 5462, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 1, 54, 48, 5428, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
