# Generated by Django 3.2.6 on 2021-09-03 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0014_auto_20210903_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 3, 47, 9, 395164, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 3, 3, 47, 9, 395113, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
