# Generated by Django 3.2.6 on 2021-09-08 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_auto_20210903_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 23, 32, 15, 407922, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 23, 32, 15, 407869, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
