# Generated by Django 3.2.6 on 2021-09-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0015_productbacklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='product_backlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto.productbacklog'),
        ),
    ]
