# Generated by Django 3.2.6 on 2021-09-08 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0016_auto_20210908_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del user story')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción del user story')),
                ('tiempoEstimado', models.PositiveIntegerField()),
                ('estado_user_story', models.CharField(choices=[('TD', 'To do'), ('DG', 'Doing'), ('DN', 'Done'), ('QA', 'Quality Assurance')], default='TD', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 23, 32, 45, 646062, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 8, 23, 32, 45, 646011, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
