# Generated by Django 3.2.6 on 2021-09-09 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0017_auto_20210908_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 22, 16, 46, 445628, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 9, 22, 16, 46, 445552, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
