# Generated by Django 3.2.6 on 2021-09-16 02:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0020_auto_20210913_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 2, 34, 58, 686600, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 2, 34, 58, 686549, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
