# Generated by Django 3.2.6 on 2021-09-16 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0021_auto_20210916_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechaFin',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 22, 20, 12, 94071, tzinfo=utc), help_text='Fecha estimada de finalización del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fechaInicio',
            field=models.DateField(default=datetime.datetime(2021, 9, 16, 22, 20, 12, 94018, tzinfo=utc), help_text='Fecha de inicialización del proyecto'),
        ),
    ]
