from sso.models import User
from proyecto.models import RolProyecto,Proyecto,ProductBacklog,ProyectUser,Sprint,UserStory,HistorialUS,Daily
User1 = User.objects.get(pk=111)
User2 = User.objects.get(pk=112)
User3 = User.objects.get(pk=113)
User4 = User.objects.get(pk=114)
User5 = User.objects.get(pk=115)
RolProyecto1 = RolProyecto.objects.get(pk=116)
RolProyecto2 = RolProyecto.objects.get(pk=117)
RolProyecto3 = RolProyecto.objects.get(pk=118)
RolProyecto4 = RolProyecto.objects.get(pk=119)
RolProyecto5 = RolProyecto.objects.get(pk=1110)
Proyecto1 = Proyecto.objects.get(pk=1111)
Proyecto2 = Proyecto.objects.get(pk=1112)
Proyecto3 = Proyecto.objects.get(pk=1113)
Proyecto4 = Proyecto.objects.get(pk=1114)
Proyecto5 = Proyecto.objects.get(pk=1115)
ProyectUser1 = ProyectUser.objects.get(pk=1116)
ProyectUser2 = ProyectUser.objects.get(pk=1117)
ProyectUser3 = ProyectUser.objects.get(pk=1118)
ProyectUser4 = ProyectUser.objects.get(pk=1119)
ProyectUser5 = ProyectUser.objects.get(pk=1120)
ProductBacklog1 = ProductBacklog.objects.get(pk=1121)
ProductBacklog2 = ProductBacklog.objects.get(pk=1122)
ProductBacklog3 = ProductBacklog.objects.get(pk=1123)
ProductBacklog4 = ProductBacklog.objects.get(pk=1124)
ProductBacklog5 = ProductBacklog.objects.get(pk=1125)
Sprint1 = Sprint.objects.get(pk=1126)
Sprint2 = Sprint.objects.get(pk=1127)
Sprint3 = Sprint.objects.get(pk=1128)
Sprint4 = Sprint.objects.get(pk=1129)
Sprint5 = Sprint.objects.get(pk=1130)
UserStory1 = UserStory.objects.get(pk=1131)
UserStory2 = UserStory.objects.get(pk=1132)
UserStory3 = UserStory.objects.get(pk=1133)
UserStory4 = UserStory.objects.get(pk=1134)
UserStory5 = UserStory.objects.get(pk=1135)
HistorialUS1 = HistorialUS.objects.get(pk=1136)
HistorialUS2 = HistorialUS.objects.get(pk=1137)
HistorialUS3 = HistorialUS.objects.get(pk=1138)
HistorialUS4 = HistorialUS.objects.get(pk=1139)
HistorialUS5 = HistorialUS.objects.get(pk=1140)
Daily1 = Daily.objects.get(pk=1141)
Daily2 = Daily.objects.get(pk=1142)
Daily3 = Daily.objects.get(pk=1143)
Daily4 = Daily.objects.get(pk=1144)
Daily5 = Daily.objects.get(pk=1145)
Proyecto1.owner.set(User.objects.filter(pk=111))
Proyecto2.owner.set(User.objects.filter(pk=112))
Proyecto3.owner.set(User.objects.filter(pk=113))
Proyecto4.owner.set(User.objects.filter(pk=114))
Proyecto5.owner.set(User.objects.filter(pk=115))
ProyectUser1.usuario.set(User.objects.filter(pk=111))
ProyectUser2.usuario.set(User.objects.filter(pk=112))
ProyectUser3.usuario.set(User.objects.filter(pk=113))
ProyectUser4.usuario.set(User.objects.filter(pk=114))
ProyectUser5.usuario.set(User.objects.filter(pk=115))
UserStory1.creador.set(User.objects.filter(pk=111))
UserStory2.creador.set(User.objects.filter(pk=112))
UserStory3.creador.set(User.objects.filter(pk=113))
UserStory4.creador.set(User.objects.filter(pk=114))
UserStory5.creador.set(User.objects.filter(pk=115))
RolProyecto1.proyecto.set(Proyecto.objects.filter(pk=1111))
RolProyecto2.proyecto.set(Proyecto.objects.filter(pk=1112))
RolProyecto3.proyecto.set(Proyecto.objects.filter(pk=1113))
RolProyecto4.proyecto.set(Proyecto.objects.filter(pk=1114))
RolProyecto5.proyecto.set(Proyecto.objects.filter(pk=1115))
Proyecto1.equipo_desarrollador.set(ProyectUser.objects.filter(pk=1116))
Proyecto2.equipo_desarrollador.set(ProyectUser.objects.filter(pk=1117))
Proyecto3.equipo_desarrollador.set(ProyectUser.objects.filter(pk=1118))
Proyecto4.equipo_desarrollador.set(ProyectUser.objects.filter(pk=1119))
Proyecto5.equipo_desarrollador.set(ProyectUser.objects.filter(pk=1120))
ProyectUser1.sprint.set(Sprint.objects.filter(pk=1126))
ProyectUser2.sprint.set(Sprint.objects.filter(pk=1127))
ProyectUser3.sprint.set(Sprint.objects.filter(pk=1128))
ProyectUser4.sprint.set(Sprint.objects.filter(pk=1129))
ProyectUser5.sprint.set(Sprint.objects.filter(pk=1130))
ProductBacklog1.proyecto.set(Proyecto.objects.filter(pk=1111))
ProductBacklog2.proyecto.set(Proyecto.objects.filter(pk=1112))
ProductBacklog3.proyecto.set(Proyecto.objects.filter(pk=1113))
ProductBacklog4.proyecto.set(Proyecto.objects.filter(pk=1114))
ProductBacklog5.proyecto.set(Proyecto.objects.filter(pk=1115))
Sprint1.proyecto.set(Proyecto.objects.filter(pk=1111))
Sprint2.proyecto.set(Proyecto.objects.filter(pk=1112))
Sprint3.proyecto.set(Proyecto.objects.filter(pk=1113))
Sprint4.proyecto.set(Proyecto.objects.filter(pk=1114))
Sprint5.proyecto.set(Proyecto.objects.filter(pk=1115))
UserStory1.encargado.set(ProyectUser.objects.filter(pk=1116))
UserStory2.encargado.set(ProyectUser.objects.filter(pk=1117))
UserStory3.encargado.set(ProyectUser.objects.filter(pk=1118))
UserStory4.encargado.set(ProyectUser.objects.filter(pk=1119))
UserStory5.encargado.set(ProyectUser.objects.filter(pk=1120))
UserStory1.sprint.set(Sprint.objects.filter(pk=1126))
UserStory2.sprint.set(Sprint.objects.filter(pk=1127))
UserStory3.sprint.set(Sprint.objects.filter(pk=1128))
UserStory4.sprint.set(Sprint.objects.filter(pk=1129))
UserStory5.sprint.set(Sprint.objects.filter(pk=1130))
UserStory1.product_backlog.set(ProductBacklog.objects.filter(pk=1121))
UserStory2.product_backlog.set(ProductBacklog.objects.filter(pk=1122))
UserStory3.product_backlog.set(ProductBacklog.objects.filter(pk=1123))
UserStory4.product_backlog.set(ProductBacklog.objects.filter(pk=1124))
UserStory5.product_backlog.set(ProductBacklog.objects.filter(pk=1125))
HistorialUS1.us_fk.set(UserStory.objects.filter(pk=1131))
HistorialUS2.us_fk.set(UserStory.objects.filter(pk=1132))
HistorialUS3.us_fk.set(UserStory.objects.filter(pk=1133))
HistorialUS4.us_fk.set(UserStory.objects.filter(pk=1134))
HistorialUS5.us_fk.set(UserStory.objects.filter(pk=1135))
Daily1.user_story.set(UserStory.objects.filter(pk=1131))
Daily2.user_story.set(UserStory.objects.filter(pk=1132))
Daily3.user_story.set(UserStory.objects.filter(pk=1133))
Daily4.user_story.set(UserStory.objects.filter(pk=1134))
Daily5.user_story.set(UserStory.objects.filter(pk=1135))
Daily1.sprint.set(Sprint.objects.filter(pk=1126))
Daily2.sprint.set(Sprint.objects.filter(pk=1127))
Daily3.sprint.set(Sprint.objects.filter(pk=1128))
Daily4.sprint.set(Sprint.objects.filter(pk=1129))
Daily5.sprint.set(Sprint.objects.filter(pk=1130))
User1.save()
User2.save()
User3.save()
User4.save()
User5.save()
RolProyecto1.save()
RolProyecto2.save()
RolProyecto3.save()
RolProyecto4.save()
RolProyecto5.save()
Proyecto1.save()
Proyecto2.save()
Proyecto3.save()
Proyecto4.save()
Proyecto5.save()
ProyectUser1.save()
ProyectUser2.save()
ProyectUser3.save()
ProyectUser4.save()
ProyectUser5.save()
ProductBacklog1.save()
ProductBacklog2.save()
ProductBacklog3.save()
ProductBacklog4.save()
ProductBacklog5.save()
Sprint1.save()
Sprint2.save()
Sprint3.save()
Sprint4.save()
Sprint5.save()
UserStory1.save()
UserStory2.save()
UserStory3.save()
UserStory4.save()
UserStory5.save()
HistorialUS1.save()
HistorialUS2.save()
HistorialUS3.save()
HistorialUS4.save()
HistorialUS5.save()
Daily1.save()
Daily2.save()
Daily3.save()
Daily4.save()
Daily5.save()