from sso import models
from proyecto import models
User1 = models.User.objects.get(pk=1)
User2 = models.User.objects.get(pk=2)
User3 = models.User.objects.get(pk=3)
User4 = models.User.objects.get(pk=4)
User5 = models.User.objects.get(pk=5)
RolProyecto1 = models.RolProyecto.objects.get(pk=6)
RolProyecto2 = models.RolProyecto.objects.get(pk=7)
RolProyecto3 = models.RolProyecto.objects.get(pk=8)
RolProyecto4 = models.RolProyecto.objects.get(pk=9)
RolProyecto5 = models.RolProyecto.objects.get(pk=10)
Proyecto1 = models.Proyecto.objects.get(pk=11)
Proyecto2 = models.Proyecto.objects.get(pk=12)
Proyecto3 = models.Proyecto.objects.get(pk=13)
Proyecto4 = models.Proyecto.objects.get(pk=14)
Proyecto5 = models.Proyecto.objects.get(pk=15)
ProyectUser1 = models.ProyectUser.objects.get(pk=16)
ProyectUser2 = models.ProyectUser.objects.get(pk=17)
ProyectUser3 = models.ProyectUser.objects.get(pk=18)
ProyectUser4 = models.ProyectUser.objects.get(pk=19)
ProyectUser5 = models.ProyectUser.objects.get(pk=20)
ProductBacklog1 = models.ProductBacklog.objects.get(pk=21)
ProductBacklog2 = models.ProductBacklog.objects.get(pk=22)
ProductBacklog3 = models.ProductBacklog.objects.get(pk=23)
ProductBacklog4 = models.ProductBacklog.objects.get(pk=24)
ProductBacklog5 = models.ProductBacklog.objects.get(pk=25)
Sprint1 = models.Sprint.objects.get(pk=26)
Sprint2 = models.Sprint.objects.get(pk=27)
Sprint3 = models.Sprint.objects.get(pk=28)
Sprint4 = models.Sprint.objects.get(pk=29)
Sprint5 = models.Sprint.objects.get(pk=30)
UserStory1 = models.UserStory.objects.get(pk=31)
UserStory2 = models.UserStory.objects.get(pk=32)
UserStory3 = models.UserStory.objects.get(pk=33)
UserStory4 = models.UserStory.objects.get(pk=34)
UserStory5 = models.UserStory.objects.get(pk=35)
HistorialUS1 = models.HistorialUS.objects.get(pk=36)
HistorialUS2 = models.HistorialUS.objects.get(pk=37)
HistorialUS3 = models.HistorialUS.objects.get(pk=38)
HistorialUS4 = models.HistorialUS.objects.get(pk=39)
HistorialUS5 = models.HistorialUS.objects.get(pk=40)
Daily1 = models.Daily.objects.get(pk=41)
Daily2 = models.Daily.objects.get(pk=42)
Daily3 = models.Daily.objects.get(pk=43)
Daily4 = models.Daily.objects.get(pk=44)
Daily5 = models.Daily.objects.get(pk=45)
User1.save()
User2.save()
User3.save()
User4.save()
User5.save()
RolProyecto1.save()
RolProyecto2.save()
RolProyecto3.save()
RolProyecto4.save()
RolProyecto5.save()
Proyecto1.save()
Proyecto2.save()
Proyecto3.save()
Proyecto4.save()
Proyecto5.save()
ProyectUser1.save()
ProyectUser2.save()
ProyectUser3.save()
ProyectUser4.save()
ProyectUser5.save()
ProductBacklog1.save()
ProductBacklog2.save()
ProductBacklog3.save()
ProductBacklog4.save()
ProductBacklog5.save()
Sprint1.save()
Sprint2.save()
Sprint3.save()
Sprint4.save()
Sprint5.save()
UserStory1.save()
UserStory2.save()
UserStory3.save()
UserStory4.save()
UserStory5.save()
HistorialUS1.save()
HistorialUS2.save()
HistorialUS3.save()
HistorialUS4.save()
HistorialUS5.save()
Daily1.save()
Daily2.save()
Daily3.save()
Daily4.save()
Daily5.save()
RolProyecto1.proyecto.add(Proyecto1)
RolProyecto2.proyecto.add(Proyecto2)
RolProyecto3.proyecto.add(Proyecto3)
RolProyecto4.proyecto.add(Proyecto4)
RolProyecto5.proyecto.add(Proyecto5)
Proyecto1.owner.add(User1)
Proyecto2.owner.add(User2)
Proyecto3.owner.add(User3)
Proyecto4.owner.add(User4)
Proyecto5.owner.add(User5)
Proyecto1.equipo_desarrollador.add(ProyectUser1)
Proyecto2.equipo_desarrollador.add(ProyectUser2)
Proyecto3.equipo_desarrollador.add(ProyectUser3)
Proyecto4.equipo_desarrollador.add(ProyectUser4)
Proyecto5.equipo_desarrollador.add(ProyectUser5)
ProyectUser1.usuario.add(User1)
ProyectUser2.usuario.add(User2)
ProyectUser3.usuario.add(User3)
ProyectUser4.usuario.add(User4)
ProyectUser5.usuario.add(User5)
ProyectUser1.sprint.add(Sprint1)
ProyectUser2.sprint.add(Sprint2)
ProyectUser3.sprint.add(Sprint3)
ProyectUser4.sprint.add(Sprint4)
ProyectUser5.sprint.add(Sprint5)
ProductBacklog1.proyecto.add(Proyecto1)
ProductBacklog2.proyecto.add(Proyecto2)
ProductBacklog3.proyecto.add(Proyecto3)
ProductBacklog4.proyecto.add(Proyecto4)
ProductBacklog5.proyecto.add(Proyecto5)
Sprint1.proyecto.add(Proyecto1)
Sprint2.proyecto.add(Proyecto2)
Sprint3.proyecto.add(Proyecto3)
Sprint4.proyecto.add(Proyecto4)
Sprint5.proyecto.add(Proyecto5)
UserStory1.encargado.add(ProyectUser1)
UserStory2.encargado.add(ProyectUser2)
UserStory3.encargado.add(ProyectUser3)
UserStory4.encargado.add(ProyectUser4)
UserStory5.encargado.add(ProyectUser5)
UserStory1.creador.add(User1)
UserStory2.creador.add(User2)
UserStory3.creador.add(User3)
UserStory4.creador.add(User4)
UserStory5.creador.add(User5)
UserStory1.sprint.add(Sprint1)
UserStory2.sprint.add(Sprint2)
UserStory3.sprint.add(Sprint3)
UserStory4.sprint.add(Sprint4)
UserStory5.sprint.add(Sprint5)
UserStory1.product_backlog.add(ProductBacklog1)
UserStory2.product_backlog.add(ProductBacklog2)
UserStory3.product_backlog.add(ProductBacklog3)
UserStory4.product_backlog.add(ProductBacklog4)
UserStory5.product_backlog.add(ProductBacklog5)
HistorialUS1.us_fk.add(UserStory1)
HistorialUS2.us_fk.add(UserStory2)
HistorialUS3.us_fk.add(UserStory3)
HistorialUS4.us_fk.add(UserStory4)
HistorialUS5.us_fk.add(UserStory5)
Daily1.user_story.add(UserStory1)
Daily2.user_story.add(UserStory2)
Daily3.user_story.add(UserStory3)
Daily4.user_story.add(UserStory4)
Daily5.user_story.add(UserStory5)
Daily1.sprint.add(Sprint1)
Daily2.sprint.add(Sprint2)
Daily3.sprint.add(Sprint3)
Daily4.sprint.add(Sprint4)
Daily5.sprint.add(Sprint5)
User1.save()
User2.save()
User3.save()
User4.save()
User5.save()
RolProyecto1.save()
RolProyecto2.save()
RolProyecto3.save()
RolProyecto4.save()
RolProyecto5.save()
Proyecto1.save()
Proyecto2.save()
Proyecto3.save()
Proyecto4.save()
Proyecto5.save()
ProyectUser1.save()
ProyectUser2.save()
ProyectUser3.save()
ProyectUser4.save()
ProyectUser5.save()
ProductBacklog1.save()
ProductBacklog2.save()
ProductBacklog3.save()
ProductBacklog4.save()
ProductBacklog5.save()
Sprint1.save()
Sprint2.save()
Sprint3.save()
Sprint4.save()
Sprint5.save()
UserStory1.save()
UserStory2.save()
UserStory3.save()
UserStory4.save()
UserStory5.save()
HistorialUS1.save()
HistorialUS2.save()
HistorialUS3.save()
HistorialUS4.save()
HistorialUS5.save()
Daily1.save()
Daily2.save()
Daily3.save()
Daily4.save()
Daily5.save()