# Generated by Django 3.2.6 on 2021-08-30 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('p_is_user', 'El usuario es un usuario registrado que se le asignó un rol. Con este permiso tiene la posibilidad de ver más en el sistema.')], 'verbose_name_plural': 'users'},
        ),
    ]
