# Generated by Django 3.2.6 on 2021-08-16 14:49

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='burnDownChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codComentario', models.CharField(max_length=50)),
                ('codUserStory', models.IntegerField(max_length=50)),
                ('codProyecto', models.IntegerField(max_length=50)),
                ('descripcion', models.IntegerField(max_length=50)),
                ('fecha', models.DateField(verbose_name=datetime.date(2021, 8, 16))),
            ],
        ),
        migrations.CreateModel(
            name='historialCambiosUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='usuarioProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='userStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUserStory', models.CharField(max_length=50)),
                ('codigoUserStory', models.CharField(max_length=50)),
                ('listaParticipantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
                ('descripcionUserStory', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
                ('estimacion', models.IntegerField()),
                ('tiempoEmpleado', models.IntegerField()),
                ('comentarios', models.ManyToManyField(to='sso.comentario')),
            ],
        ),
    ]
