# Generated by Django 3.2.6 on 2021-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0002_burndownchart_comentario_historialcambiosus_proyecto_rol_sprint_userstory_usuario_usuarioproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='codProyecto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='codUserStory',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
    ]
