# Generated by Django 3.2.6 on 2021-08-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0003_auto_20210816_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='comentarios',
            field=models.ManyToManyField(related_name='comentario', to='sso.comentario'),
        ),
    ]
