# Generated by Django 3.2.6 on 2021-08-18 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_alter_userstory_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='sprint',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 18)),
        ),
        migrations.DeleteModel(
            name='userStory',
        ),
    ]
