# Generated by Django 3.2.6 on 2021-08-18 00:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_alter_userstory_comentarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'permisos',
            },
        ),
        migrations.CreateModel(
            name='RolSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Define el nombre del Rol de sistema', max_length=50, verbose_name='Nombre del Rol')),
                ('permisos', models.ManyToManyField(to='sso.Permiso')),
            ],
            options={
                'verbose_name_plural': 'system_roles',
            },
        ),
        migrations.DeleteModel(
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='sprint',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 18)),
        ),
        migrations.DeleteModel(
            name='userStory',
        ),
    ]
