# Generated by Django 3.2.6 on 2021-08-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_alter_userstory_comentarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proyecto',
        ),
        migrations.DeleteModel(
            name='sprint',
        ),
        migrations.DeleteModel(
            name='userStory',
        ),
    ]
