# Generated by Django 3.2.6 on 2021-08-26 22:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_auto_20210818_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolsistema',
            name='permisos',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_acceder_ususario', 'Test de prueba')], 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 26)),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolSistema',
        ),
    ]
