# Generated by Django 3.2.6 on 2021-08-23 16:37

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0005_auto_20210818_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 23)),
        ),
        migrations.CreateModel(
            name='userStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUserStory', models.CharField(max_length=50)),
                ('codigoUserStory', models.CharField(max_length=50)),
                ('listaParticipantes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), max_length=10, size=None)),
                ('descripcionUserStory', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=10)),
                ('estimacion', models.IntegerField()),
                ('tiempoEmpleado', models.IntegerField()),
                ('comentarios', models.ManyToManyField(related_name='comentario', to='sso.comentario')),
            ],
        ),
        migrations.CreateModel(
            name='sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSprint', models.CharField(max_length=50)),
                ('codSprint', models.CharField(max_length=50)),
                ('nroUserStories', models.IntegerField()),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('listaStories', models.ManyToManyField(max_length=100, to='sso.userStory')),
            ],
        ),
    ]
