# Generated by Django 3.2.6 on 2021-08-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_auto_20210823_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='burnDownChart',
        ),
        migrations.DeleteModel(
            name='historialCambiosUS',
        ),
        migrations.DeleteModel(
            name='rol',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='listaStories',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='comentarios',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.DeleteModel(
            name='usuarioProyecto',
        ),
        migrations.DeleteModel(
            name='comentario',
        ),
        migrations.DeleteModel(
            name='sprint',
        ),
        migrations.DeleteModel(
            name='userStory',
        ),
    ]
