# Generated by Django 3.2.6 on 2021-08-20 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_auto_20210820_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('custom_acceder_ususario', 'Test de prueba')], 'verbose_name_plural': 'users'},
        ),
    ]
