# Generated by Django 3.2.6 on 2021-08-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_alter_comentario_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_administrator',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
    ]
