# Generated by Django 3.2.6 on 2021-08-27 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_auto_20210826_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 27)),
        ),
    ]
