# Generated by Django 3.2.6 on 2021-08-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0007_user_is_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name_plural': 'permisos',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='RolSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Define el nombre del Rol de sistema', max_length=50, verbose_name='Nombre del Rol')),
                ('permisos', models.ManyToManyField(to='sso.Permiso')),
            ],
            options={
                'verbose_name_plural': 'system_roles',
            },
        ),
    ]
