# Generated by Django 3.2.6 on 2021-08-24 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0007_alter_user_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolsistema',
            name='permisos',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateField(verbose_name=datetime.date(2021, 8, 24)),
        ),
        migrations.DeleteModel(
            name='Permiso',
        ),
        migrations.DeleteModel(
            name='RolSistema',
        ),
    ]
